name: 'ArgoCD Deployment Trigger'

on:
  repository_dispatch:
    types: [update-images]

jobs:
  update-helm-images:
    runs-on: ubuntu-latest
    environment: production # Manual Approval Gate
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update values.yaml
        run: |
          sed -i "s|.*# IMAGE_AI|  ai: jdcarenestnewacr.azurecr.io/ai:${{ github.event.client_payload.image_tag }} # IMAGE_AI|g" carenest/values.yaml
          sed -i "s|.*# IMAGE_AUTH|  auth: jdcarenestnewacr.azurecr.io/auth:${{ github.event.client_payload.image_tag }} # IMAGE_AUTH|g" carenest/values.yaml
          sed -i "s|.*# IMAGE_APPOINTMENT|  appointment: jdcarenestnewacr.azurecr.io/appointment:${{ github.event.client_payload.image_tag }} # IMAGE_APPOINTMENT|g" carenest/values.yaml
          sed -i "s|.*# IMAGE_PHARMACY|  pharmacy: jdcarenestnewacr.azurecr.io/pharmacy:${{ github.event.client_payload.image_tag }} # IMAGE_PHARMACY|g" carenest/values.yaml
          sed -i "s|.*# IMAGE_NOTIFY|  notify: jdcarenestnewacr.azurecr.io/notify:${{ github.event.client_payload.image_tag }} # IMAGE_NOTIFY|g" carenest/values.yaml
          sed -i "s|.*# IMAGE_FRONTEND|  frontend: jdcarenestnewacr.azurecr.io/frontend:${{ github.event.client_payload.image_tag }} # IMAGE_FRONTEND|g" carenest/values.yaml

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add carenest/values.yaml
          git commit -m "Update image tags to ${{ github.event.client_payload.image_tag }}"
          git push

      - name: Pipeline Status Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'ArgoCD Update Pipeline finished with status: ${{ job.status }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
